name: RegexFilter
main: hu.banyamesterseg.regexfilter.RegexFilterPlugin
authors: [sph, HazeDev]
version: 1.7.0
api-version: 1.13
website: 'https://github.com/banyamesterseg/RegexFilter'
description: 'Simple chat filter harnessing the power of Regular Expressions'
softdepend: [PlaceholderAPI]
permissions:
  regexfilter.reload:
    description: allow filterset reload
    default: op
commands:
  regexfilter:
   description: do everything regexfilter related
   usage: /regexfilter reload